apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-backend
  namespace: nvidia-retail-ai
  labels:
    app: agent-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-backend
  template:
    metadata:
      labels:
        app: agent-backend
        component: backend
    spec:
      serviceAccountName: agent-backend-sa
      containers:
      - name: agent-backend
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/nvidia-retail-ai/agent-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8000"
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: google-api-key
        - name: NVIDIA_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: nvidia-api-key
        - name: QDRANT_URL
          value: "http://qdrant:6333"
        - name: NVIDIA_EMBEDDING_URL
          value: "https://integrate.api.nvidia.com/v1/embeddings"
        - name: NVIDIA_RERANKER_URL
          value: "https://integrate.api.nvidia.com/v1/ranking"
        - name: COLLECTION_NAME
          value: "image_embeddings"
        - name: EMBEDDING_DIM
          value: "4096"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: agent-backend
  namespace: nvidia-retail-ai
  labels:
    app: agent-backend
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: agent-backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-backend-sa
  namespace: nvidia-retail-ai
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/nvidia-retail-ai-agent-role
